### ISSUE TITLE
Tried creating a cube compound with C3xI / ExI and got an assert

### ISSUE THREAD

**Issue by marcelteun** [marcelteun/Orbitit#10]
Steps:
1. Create orbit scene
2. Import cube which share a 2-fold axis with the z-axis
3. Choose final symmetry CnxI with n=3
4. Choose stabilizer symmetry ExI
5. Apply symmetry

This lead to the following assert using 5416728f398c880c78defaa31ec52d04ed20d073

Traceback (most recent call last):
  File "/home/marceltn/self/fromGitHub/Orbitit/orbitit/scene_orbit.py", line 405, in on_apply_sym
    self.add_col_gui()
  File "/home/marceltn/self/fromGitHub/Orbitit/orbitit/scene_orbit.py", line 264, in add_col_gui
    for p in self.orbit.lower_order_stab_props:
  File "/home/marceltn/self/fromGitHub/Orbitit/orbitit/orbit.py", line 185, in lower_order_stab_props
    self.__losp_cache = self.__losp()
  File "/home/marceltn/self/fromGitHub/Orbitit/orbitit/orbit.py", line 200, in __losp
    self.final_sym_alt = self.final.direct_parent(setup=self.final.direct_parent_setup)
  File "/home/marceltn/self/fromGitHub/Orbitit/orbitit/isometry.py", line 693, in __init__
    self.chk_setup(setup)
  File "/home/marceltn/self/fromGitHub/Orbitit/orbitit/isometry.py", line 510, in chk_setup
    assert  k == 'n' and self.n, (
AssertionError: Unknown parameter n in setup = {'n': 3, 'axis': orbitit.geomtypes.Vec3([0, 0, 1])} for C0

**Comment by marcelteun** [comment]
Fixed in b0064a708fa29c566d36ed4d91b62e2b7ee16ac7
