### ISSUE TITLE
In the scene: heptagons from kite, great icosahedron I get an IndexError for Great Stellated Dodecahedron

### ISSUE THREAD

**Issue by marcelteun** [marcelteun/Orbitit#11]
Under "Special Solid Positions", choose "Great Stellated Dodecahedron"
Get the following log:
WARNING@<heptagons.py:3113> kite2Hept: negative sqrt requested
Traceback (most recent call last):
  File "/home/marceltn/self/fromGitHub/Orbitit/orbitit/Scene_EqlHeptA5xI_GI.py", line 381, in onSpecialSolidPos
    this.shape.angle = angle
  File "/home/marceltn/self/fromGitHub/Orbitit/orbitit/heptagons.py", line 4840, in angle
    self.set_angle(a)
  File "/home/marceltn/self/fromGitHub/Orbitit/orbitit/Scene_EqlHeptA5xI_GI.py", line 77, in set_angle
    super().set_angle(a)
  File "/home/marceltn/self/fromGitHub/Orbitit/orbitit/heptagons.py", line 4848, in set_angle
    self.set_vs()
  File "/home/marceltn/self/fromGitHub/Orbitit/orbitit/Scene_EqlHeptA5xI_GI.py", line 122, in set_vs
    v3 = heptN[0][3]
IndexError: tuple index out of range

**Comment by marcelteun** [comment]
Pushed fix, waiting for auto test
