### ISSUE TITLE
Inprecision bug for orbiting scene

### ISSUE THREAD

**Issue by marcelteun** [marcelteun/Orbitit#21]
When transforms are a bit different, but represent the same operation anyway, the orbit scene will fail.

Here is an example log, where instead of 12 transforms for the orbit 16 transforms are used. In that case the colour fails, since the groupd isn't really closed anymore:

INFO@<scene_orbit.py:681> opening file: faceted_snub_dodecahedron_5.json
****** ----- check whether set is in set --------------
INFO@<geom_3d.py:3001> Applying an orbit of order 60
INFO@<scene_orbit.py:690> read 5 vs and 1 fs.
INFO@<geomtypes.py:757> Note: transforms considered equal, but hashes will not be for
Rotation of 72 degrees around [0, -0.8506508083448, -0.5257311121309] and
Rotation of 72 degrees around [0, -0.850650808352, -0.5257311121191]
INFO@<geomtypes.py:757> Note: transforms considered equal, but hashes will not be for
Rotation of 144 degrees around [0, -0.8506508083448, -0.5257311121309] and
Rotation of 144 degrees around [0, -0.850650808352, -0.5257311121191]
INFO@<geomtypes.py:757> Note: transforms considered equal, but hashes will not be for
Rotation of 144 degrees around [0, 0.8506508083448, 0.5257311121309] and
Rotation of 144 degrees around [0, 0.850650808352, 0.5257311121191]
INFO@<geomtypes.py:757> Note: transforms considered equal, but hashes will not be for
Rotation of 72 degrees around [0, 0.8506508083448, 0.5257311121309] and
Rotation of 72 degrees around [0, 0.850650808352, 0.5257311121191]
****** ----- check whether set is in set --------------
INFO@<geom_3d.py:3001> Applying an orbit of order 16
Traceback (most recent call last):
  File "/home/marceltn/self/fromGitHub/Orbitit/orbitit/scene_orbit.py", line 378, in on_apply_sym
    self.add_col_gui()
  File "/home/marceltn/self/fromGitHub/Orbitit/orbitit/scene_orbit.py", line 260, in add_col_gui
    self.on_no_of_col_select(self.col_guis[-1])
  File "/home/marceltn/self/fromGitHub/Orbitit/orbitit/scene_orbit.py", line 472, in on_no_of_col_select
    assert l0 != 0, 'no higher order stabilisers found'
AssertionError: no higher order stabilisers found

**Comment by marcelteun** [comment]
It seems that this line  if orbitit/geom_3d.py is failing.
        fs_orbit = [coset.get_one() for coset in fs_quotient_set]
Since the print "****** ----- check whether set is in set --------------" was added just before.

**Comment by marcelteun** [comment]
[faceted_snub_dodecahedron_5.json](https://github.com/marcelteun/Orbitit/files/14823597/faceted_snub_dodecahedron_5.json)

**Comment by marcelteun** [comment]
Attached above, the failing JSON file

**Comment by marcelteun** [comment]
The attached file will not reproduce the error (anymore). Actually it applies 60 symmetries, since the stabliser symmetry is E. I tried with C5, but that worked anyway: it applied 12 symmetries. E.g. the attached file just works

[faceted_snub_dodecahedron_5_1.json](https://github.com/user-attachments/files/21333713/faceted_snub_dodecahedron_5_1.json)

**Comment by marcelteun** [comment]
Will close this issue, since I cannot reproduce
