### ISSUE TITLE
Cannot use Cn as subgroup in orbit scene

### ISSUE THREAD

**Issue by marcelteun** [marcelteun/Orbitit#22]
**Got a stack call:**
Traceback (most recent call last):
  File "/home/marceltn/self/fromGitHub/Orbitit/orbitit/geom_gui.py", line 1362, in on_set_sym
    self.add_setup_gui()
  File "/home/marceltn/self/fromGitHub/Orbitit/orbitit/geom_gui.py", line 1337, in add_setup_gui
    self.panel, init["lab"], init=sym_setup[init["par"]]
KeyError: 'n'

**Version:**
81af0df (HEAD -> wip_compounds) S4A4 compounds: add n|Dn/C2

**Reproduce:**
I chose a tetrahedron as descriptive (in std orientation) and Dn as final symmetry (0, 0, 1) and (1, 0, 0) as setup. Then I needed C3 as subgroup so I chose Cn. That's when the stack trace appeared

**Comment by marcelteun** [comment]
Hmm. I cannot reproduce on tag 0.6.7. There is no Cn for the stabilisers. I thought that perhaps before 0.6.7 one needed to press the "Regenerate Stabilisers" first, since in 0.6.7 they are regenerated automatically after updating n in the final symmetry, but even on 0.6.6 I wasn't able to reproduce.

**Comment by marcelteun** [comment]
Will close, since I am unable to reproduce
