### ISSUE TITLE
Isometry: dihedral and cyclic derived symmetries with default values cannot be loaded from JSON

### ISSUE THREAD

**Issue by marcelteun** [marcelteun/Orbitit#6]
The patch fda4ad6d5c562c8a92018f6e78888b690bd2601c solved the problem for Cn and Dn, but C2nC2, DnCn, CnxI, D2nDn and DnxI probably still have the same problem, which is:

- Create a model in the orbit scene.-
- Use a stabilizer symmetry from one of the above.
- Use the defaults.-
- Apply the symmetry. 
- Save as JSON.
- Import the JSON into the orbit scene
- Check the logs

**Comment by marcelteun** [comment]
It seems this is partly solved by the patch mentioned in the issue, thought there are more problems:
E.g. a cube_3_C6C3_C2C1.json
`{"class": "orbit_shape", "data": {"cols": [[0.253906, 0.410156, 0.878906], [0.601562, 0.800781, 0.195312], [0.863281, 0.625, 0.863281]], "final_sym": {"class": "C2nCn", "data": {"generator": {"axis": [0, 0, 1], "n": 3}}}, "fs": [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15], [16, 17, 18, 19], [20, 21, 22, 23]], "name": "cube_3_C6C3_C2C1.json", "stab_sym": {"class": "C2C1", "data": {"generator": {"axis": [0, 0, 1]}}}, "vs": [[0, -1, 1.414213562373], [1.414213562373, -1, 0], [1.414213562373, 1, 0], [0, 1, 1.414213562373], [0, 1, 1.414213562373], [-1.414213562373, 1, 0], [-1.414213562373, -1, 0], [0, -1, 1.414213562373], [0, -1, -1.414213562373], [1.414213562373, -1, 0], [0, -1, 1.414213562373], [-1.414213562373, -1, 0], [0, 1, -1.414213562373], [-1.414213562373, 1, 0], [0, 1, 1.414213562373], [1.414213562373, 1, 0], [1.414213562373, -1, 0], [0, -1, -1.414213562373], [0, 1, -1.414213562373], [1.414213562373, 1, 0], [-1.414213562373, 1, 0], [0, 1, -1.414213562373], [0, -1, -1.414213562373], [-1.414213562373, -1, 0]]}}`
gives:
Traceback (most recent call last):
  File "/home/marceltn/self/fromGitHub/Orbitit/orbitit/scene_orbit.py", line 405, in on_apply_sym
    self.add_col_gui()
  File "/home/marceltn/self/fromGitHub/Orbitit/orbitit/scene_orbit.py", line 264, in add_col_gui
    for p in self.orbit.lower_order_stab_props:
  File "/home/marceltn/self/fromGitHub/Orbitit/orbitit/orbit.py", line 185, in lower_order_stab_props
    self.__losp_cache = self.__losp()
  File "/home/marceltn/self/fromGitHub/Orbitit/orbitit/orbit.py", line 200, in __losp
    self.final_sym_alt = self.final.direct_parent(setup=self.final.direct_parent_setup)

**Comment by marcelteun** [comment]
Cannot reproduce the problem with 3_C6C3_C2C1. Perhaps this was related to #10 . Got that error first, then this. After restarting and importing the JSON file, no error is seen.

That issue is fixed now and I tried with sub-groups C2cCn, CnxI, DnCn, D2nDn and DnxI stabilizer groups and no errors were seen importing. Will close the issue
